#version 430
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0, rgba16f) uniform imageCube outCube;
uniform float uTime;

void main() {
    uvec3 gid = gl_GlobalInvocationID;
    ivec2 size = ivec2(imageSize(outCube).xy);

    if(gid.x >= uint(size.x) || gid.y >= uint(size.y)) return;

    vec4 color;
    float t = uTime * 0.5; // velocidade de animação

    if(gid.z == 0) color = vec4(sin(t),0,0,1);
    else if(gid.z == 1) color = vec4(0,cos(t),0,1);
    else if(gid.z == 2) color = vec4(0,0,sin(t*0.7),1);
    else if(gid.z == 3) color = vec4(cos(t*0.3),cos(t*0.5),0,1);
    else if(gid.z == 4) color = vec4(sin(t*0.9),0,sin(t*0.4),1);
    else color = vec4(0,cos(t*1.1),cos(t*0.8),1);

    imageStore(outCube, ivec3(gid.xy, gid.z), color);
}
