#pragma once

#include "RenderSystem.h" 
#include "MoveSystem.h"
#include "Lighting/LightSystem.h" 
#include "CameraSystem.h"
#include "PostProcessSystem.h" 
#include "GlobalUniformSystem.h" 
#include "PickingSystem.h" 
#include "DayNightSystem.h"  
#include "ComputeSyncSystem.h"  
#include "TransformSystem.h"  
#include "EndLoopSystem.h" 
#include "AABBSystem.h"   
#include "DebugRenderer.h"   
#include "TextRender/TextRenderSystem.h"  