#version 430

// Tamanho do work group
//layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

// Cubemaps de entrada (HDR)
layout(binding = 0) uniform samplerCube prevCube;
layout(binding = 1) uniform samplerCube nextCube;

// Cubemap de saída
layout(binding = 2, rgba16f) uniform imageCube outCube;

// Parâmetros de interpolação
uniform float lerpFactor;   // 0.0 -> prevCube, 1.0 -> nextCube
uniform int mipLevel;       // Nível do mipmap

layout(binding=4, offset=0) uniform atomic_uint myCounter; 



// Converte (face, uv) -> direção 3D para amostrar cubemap
vec3 uvToDir(int face, vec2 uv)
{
    float u = uv.x * 2.0 - 1.0; // -1..1
    float v = uv.y * 2.0 - 1.0;

    if(face == 0) return normalize(vec3( 1.0, -v, -u)); // +X
    if(face == 1) return normalize(vec3(-1.0, -v,  u)); // -X
    if(face == 2) return normalize(vec3( u,  1.0,  v)); // +Y
    if(face == 3) return normalize(vec3( u, -1.0, -v)); // -Y
    if(face == 4) return normalize(vec3( u, -v,  1.0)); // +Z
    if(face == 5) return normalize(vec3(-u, -v, -1.0)); // -Z

    return vec3(0.0,0.0,0.0);
}

void main()
{
    atomicCounterIncrement(myCounter);
    return;

    uvec3 gid = gl_GlobalInvocationID; // x,y = pixel, z = face
    ivec2 texSize = textureSize(prevCube, mipLevel).xy;
    if(gid.x >= uint(texSize.x) || gid.y >= uint(texSize.y)) return;

    vec2 uv = (vec2(gid.xy) + 0.5) / vec2(texSize);
    vec3 dir = uvToDir(int(gid.z), uv);

    vec3 colorPrev = textureLod(prevCube, dir, float(mipLevel)).rgb;
    vec3 colorNext = textureLod(nextCube, dir, float(mipLevel)).rgb;
    vec3 lerpedColor = mix(colorPrev, colorNext, lerpFactor);

    //imageStore(outCube, ivec3(gid), vec4(lerpedColor,1.0)); 
    imageStore(outCube, ivec3(gid), vec4(0,1,1,1.0)); 

    // Garante que todas as writes em outCube fiquem visíveis fora do compute
    memoryBarrierImage();
}
