[Window][DockSpace]
Pos=0,48
Size=1600,852
Collapsed=0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][TopBar]
Pos=0,0
Size=1600,48
Collapsed=0

[Window][Scene]
Pos=84,285
Size=818,629
Collapsed=0

[Window][Toolbar]
Pos=0,0
Size=134,50
Collapsed=0
DockId=0x00000001,0

[Window][Painel Customizável]
Pos=350,140
Size=203,183
Collapsed=0

[Window][Hierarchy]
Pos=834,162
Size=1440,810
Collapsed=0

[Window][Inspector]
Pos=1017,495
Size=237,344
Collapsed=0

[Window][File Explorer]
Pos=1099,529
Size=321,266
Collapsed=0

[Docking][Data]
DockNode  ID=0x00000001 Pos=0,0 Size=134,50
DockSpace ID=0x0FCAA000 Window=0x3DA2F1DE Pos=8,56 Size=1584,836 CentralNode=1 Selected=0xBABDAE5E

